### ISSUE TITLE
Error while installing Healthcare App 

### ISSUE THREAD

**Issue by chechani** [earthians/marley#104]
I am getting below error while installing healthcare App.

Installing healthcare...
Updating DocTypes for healthcare    : [========================================] 100%
An error occurred while installing healthcare: Could not find Row #20: Reference Document Type: Certification Application
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 344, in install_app
    _install_app(app, verbose=context.verbose)
  File "apps/frappe/frappe/installer.py", line 255, in install_app
    frappe.get_doc('Portal Settings', 'Portal Settings').sync_menu()
  File "apps/frappe/frappe/website/doctype/portal_settings/portal_settings.py", line 37, in sync_menu
    self.save()
  File "apps/frappe/frappe/model/document.py", line 277, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 310, in _save
    self._validate_links()
  File "apps/frappe/frappe/model/document.py", line 835, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg),
  File "apps/frappe/frappe/__init__.py", line 448, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "apps/frappe/frappe/__init__.py", line 427, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 382, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: Could not find Row #20: Reference Document Type: Certification Application

frappe v-14 beta 3
erpnext v-14 beta 4

**Comment by chechani** [comment]
we created a new doctype called "Certification Application" and went ahead.

No issue after that.

**Comment by akashkrishna619** [comment]
@chechani Certification Application should not be a dependency for Healthcare as it's part of the Non Profit module. couldn't replicate this when i tried setting up, maybe you also have non profit module enabled?

**Comment by chechani** [comment]
We are not using Non-Profit Module, nor it is enabled.

This error appeared when upgrading from version 13 stable to v14 beta

When doing fresh installation there is no issue.

**Comment by ChillarAnand** [comment]
Found a similar issue on another site but not able to replicate it.

```
Installing healthcare...
Updating DocTypes for healthcare    : [========================================] 100%
An error occurred while installing healthcare: Could not find Row #9: Reference Document Type: Announcement, Row #10: Reference Document Type: Course, Row #11: Reference Document Type: Assessment Plan, Row #21: Reference Document Type: Grant Application
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 414, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 282, in install_app
    frappe.get_doc("Portal Settings", "Portal Settings").sync_menu()
  File "apps/frappe/frappe/website/doctype/portal_settings/portal_settings.py", line 37, in sync_menu
    self.save()
  File "apps/frappe/frappe/model/document.py", line 298, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 331, in _save
    self._validate_links()
  File "apps/frappe/frappe/model/document.py", line 893, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "apps/frappe/frappe/__init__.py", line 521, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 489, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 441, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: Could not find Row #9: Reference Document Type: Announcement, Row #10: Reference Document Type: Course, Row #11: Reference Document Type: Assessment Plan, Row #21: Reference Document Type: Grant Application
```

While syncing portal items, this error is happening.

**Comment by ChillarAnand** [comment]
In V13, NonProfit/Education and other modules were bundled as part of ERPNext.

But in V14, users have to install it manually.

If there are any portal pages related to the above modules, app install is failing at syncing portal menu.

If portal settings are fixed, healthcare app should install.

Closing this issue. Feel free to open if you are still facing the issue.
