### ISSUE TITLE
Install health for Frappe 14, Next 14

### ISSUE THREAD

**Issue by cyrsis** [earthians/marley#174]
Try to get a experience wiht Frappe , Next 14, HR

```
bench --site demo.com install-app healthcare
```
Ran into this issues
```
Installing healthcare...
Updating DocTypes for healthcare    : [================                        ] 42%An error occurred while installing healthcare: 'function' object has no attribute '__func__'
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 450, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 293, in install_app
    sync_for(name, force=force, reset_permissions=True)
  File "apps/frappe/frappe/model/sync.py", line 80, in sync_for
    import_file_by_path(
  File "apps/frappe/frappe/modules/import_file.py", line 145, in import_file_by_path
    import_doc(
  File "apps/frappe/frappe/modules/import_file.py", line 242, in import_doc
    doc.insert()
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1092, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 920, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1274, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1256, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 917, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 410, in on_update
    self.run_module_method("on_doctype_update")
  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 495, in run_module_method
    module = load_doctype_module(self.name, self.module)
  File "apps/frappe/frappe/modules/utils.py", line 236, in load_doctype_module
    doctype_python_modules[key] = frappe.get_module(module_name)
  File "apps/frappe/frappe/__init__.py", line 1328, in get_module
    return importlib.import_module(modulename)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/frappe/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "apps/healthcare/healthcare/healthcare/doctype/patient_encounter/patient_encounter.py", line 13, in <module>
    class PatientEncounter(Document):
  File "apps/healthcare/healthcare/healthcare/doctype/patient_encounter/patient_encounter.py", line 39, in PatientEncounter
    def get_applicable_treatment_plans(encounter):
  File "apps/frappe/frappe/__init__.py", line 750, in innerfn
    fn = method.__func__
AttributeError: 'function' object has no attribute '__func__'


```

### When I ran the command again , looks like it mess up with the db

```
 File "apps/frappe/frappe/model/base_document.py", line 523, in db_insert
    raise frappe.DuplicateEntryError(self.doctype, self.name, e)
frappe.exceptions.DuplicateEntryError: ('Module Def', 'Healthcare', IntegrityError(1062, "Duplicate entry 'Healthcare' for key 'PRIMARY'"))
```

**Comment by akurungadam** [comment]
Hi @cyrsis, could you please try installation with Frappe and ERPNext `version-14` release branch? Looks like there seems to be an issue on develop branch with staticmethods being whitelisted - will post you as we get to fix this. Thanks!

**Comment by cyrsis** [comment]
> Hi @cyrsis, could you please try installation with Frappe and ERPNext `version-14` release branch? Looks like there seems to be an issue on develop branch with staticmethods being whitelisted - will post you as we get to fix this. Thanks!

Thanks Mate, Good Work
I get a new fresh environment with everything with 
```
bench get-app --branch version-14 erpnext
```
And it works

**Comment by cyrsis** [comment]
For the new comer with M1 Mac
It should mention DB actually play a big role for the frappe

```
brew install mariadb@10.8
```
Make sure have brew install mariadb@10.8 rather than 10.10
Seems everything works for now
