### ISSUE TITLE
ModuleNotFound after installing healthcare under frappe_docker

### ISSUE THREAD

**Issue by sibidharan** [earthians/marley#190]
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/serve.py", line 17, in get_response
    endpoint, renderer_instance = path_resolver.resolve()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/path_resolver.py", line 58, in resolve
    renderer_instance = renderer(endpoint, 200)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/static_page.py", line 19, in __init__
    self.set_file_path()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/static_page.py", line 26, in set_file_path
    file_path = frappe.get_app_path(app, "www") + "/" + self.path
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1356, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1373, in get_pymodule_path
    return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__ or ""), *joins)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1327, in get_module
    return importlib.import_module(modulename)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'healthcare'
```

As soon as I install the healthcare app, this error pops up. I am unable to `bench restart` either because it says it cannot find supervisorctl in its path. 

I believe I am running in production. How to make this work?

**Comment by akurungadam** [comment]
Not specific to health app, and is tracked [here](https://github.com/frappe/bench/issues/1436).
