### ISSUE TITLE
After importing Healthcare app in ERPNext throws Error: No module named 'erpnext.healthcare'

### ISSUE THREAD

**Issue by sulaimaan26** [earthians/marley#273]
### Information about bug

I am getting this error when I am into Health care module
![image](https://github.com/frappe/health/assets/49139974/36e93a56-e173-4e29-aa80-e895d501fb22)
![image](https://github.com/frappe/health/assets/49139974/c1b9aa45-89a5-4c8e-98ba-e012d267af58)

### Module

Integration with ERPNext modules

### Version

Frappe Version-
ERPNext Version-14.9.0

### Installation method

docker

### Relevant log output / Stack trace / Full Error Message.

```shell
Traceback (most recent call last):
2023-09-16 08:46:29   File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 271, in handle
2023-09-16 08:46:29     keepalive = self.handle_request(req, conn)
2023-09-16 08:46:29   File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 323, in handle_request
2023-09-16 08:46:29     respiter = self.wsgi(environ, resp.start_response)
2023-09-16 08:46:29   File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/werkzeug/local.py", line 237, in application
2023-09-16 08:46:29     return ClosingIterator(app(environ, start_response), self.cleanup)
2023-09-16 08:46:29   File "/home/frappe/frappe-bench/env/lib/python3.10/site-packages/werkzeug/wrappers/request.py", line 194, in application
2023-09-16 08:46:29     resp = f(*args[:-2] + (request,))
2023-09-16 08:46:29   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 112, in application
2023-09-16 08:46:29     response = handle_exception(e)
2023-09-16 08:46:29   File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 366, in handle_exception
2023-09-16 08:46:29     response = get_response("message", http_status_code=http_status_code)
2023-09-16 08:46:29   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/serve.py", line 26, in get_response
2023-09-16 08:46:29     response = ErrorPage(exception=e).render()
2023-09-16 08:46:29   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/error_page.py", line 7, in __init__
2023-09-16 08:46:29     super().__init__(path=path, http_status_code=http_status_code)
2023-09-16 08:46:29   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 45, in __init__
2023-09-16 08:46:29     self.set_template_path()
2023-09-16 08:46:29   File "/home/frappe/frappe-bench/apps/frappe/frappe/website/page_renderers/template_page.py", line 54, in set_template_path
2023-09-16 08:46:29     app_path = frappe.get_app_path(app)
2023-09-16 08:46:29   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1371, in get_app_path
2023-09-16 08:46:29     return get_pymodule_path(app_name, *joins)
2023-09-16 08:46:29   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1388, in get_pymodule_path
2023-09-16 08:46:29     return os.path.join(os.path.dirname(get_module(scrub(modulename)).__file__ or ""), *joins)
2023-09-16 08:46:29   File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1342, in get_module
2023-09-16 08:46:29     return importlib.import_module(modulename)
2023-09-16 08:46:29   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2023-09-16 08:46:29     return _bootstrap._gcd_import(name[level:], package, level)
2023-09-16 08:46:29   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2023-09-16 08:46:29   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2023-09-16 08:46:29   File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
2023-09-16 08:46:29 ModuleNotFoundError: No module named 'healthcare'
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by sulaimaan26** [comment]
Any update?

**Comment by kalungia** [comment]
Did you do any upgrades, to healthycare app. But you can reinstall the site that should fix it.

**Comment by akurungadam** [comment]
IMO, this can happen on version-13 benches.. as you see `erpnext.healthcre`  - on version-14 this shouldn't happen as the module was moved out as an app. could you please check once again? closing this for now as installation seem to be seamless so far
