### ISSUE TITLE
Removing Customizations for Frappe Health failed

### ISSUE THREAD

**Issue by AhmedHassanEldesoky** [earthians/marley#274]
### Information about bug

I'm trying to uninstall healthcare app from my site but it gives me this error.
I used this commend
$ bench --site erp.alpharalph.com uninstall-app healthcare --no-backup --force --yes

### Module

Setup / Configuration, Integration with ERPNext modules

### Version

erpnext 14.x.x-develop
frappe 15.x.x-develop
healthcare 15.0.0-dev

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
Uninstalling App healthcare from Site erp.alpharalph.com...
Removing customizations created by Frappe Health...
Removing Customizations for Frappe Health failed due to an error. Please try again or report the issue on https://github.com/frappe/health/issues/new if not resolved.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/var/www/bench/frappe/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/var/www/bench/frappe/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/var/www/bench/frappe/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/var/www/bench/frappe/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/var/www/bench/frappe/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/www/bench/frappe/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/www/bench/frappe/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/www/bench/frappe/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/var/www/bench/frappe/env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/var/www/bench/frappe/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/var/www/bench/frappe/apps/frappe/frappe/commands/site.py", line 859, in uninstall
    remove_app(app_name=app, dry_run=dry_run, yes=yes, no_backup=no_backup, force=force)
  File "/var/www/bench/frappe/apps/frappe/frappe/installer.py", line 376, in remove_app
    frappe.get_attr(before_uninstall)()
  File "/var/www/bench/frappe/apps/healthcare/healthcare/uninstall.py", line 20, in before_uninstall
    raise e
  File "/var/www/bench/frappe/apps/healthcare/healthcare/uninstall.py", line 10, in before_uninstall
    remove_customizations()
  File "/var/www/bench/frappe/apps/healthcare/healthcare/setup.py", line 180, in before_uninstall
    domain = frappe.get_doc("Domain", "Healthcare")
  File "/var/www/bench/frappe/apps/frappe/frappe/__init__.py", line 1254, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/var/www/bench/frappe/apps/frappe/frappe/model/document.py", line 80, in get_doc
    return controller(*args, **kwargs)
  File "/var/www/bench/frappe/apps/frappe/frappe/model/document.py", line 121, in __init__
    self.load_from_db()
  File "/var/www/bench/frappe/apps/frappe/frappe/model/document.py", line 173, in load_from_db
    frappe.throw(
  File "/var/www/bench/frappe/apps/frappe/frappe/__init__.py", line 559, in throw
    msgprint(
  File "/var/www/bench/frappe/apps/frappe/frappe/__init__.py", line 531, in msgprint
    _raise_exception()
  File "/var/www/bench/frappe/apps/frappe/frappe/__init__.py", line 480, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.DoesNotExistError: Domain Healthcare not found
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sajinsr** [comment]
@AhmedHassanEldesoky Let us know if this issue still exist

**Comment by Sajinsr** [comment]
Hi, is this issue still exist? the repo is now available at https://github.com/earthians/marley
can you check the remote and pull the latest and try again? closing this issue for now.
