### ISSUE TITLE
AttributeError in Sales Invoice

### ISSUE THREAD

**Issue by Yogeshwaran2210** [earthians/marley#346]
### Information about bug

Server Error
AttributeError: 'HealthcareSalesInvoice' object has no attribute 'service_unit'...
In Some Doctypes in ERP Next version 14 (Sales Invoice). How to solve?

### Module

Outpatient Module, Inpatient ADT, Regional / Other Integrations

### Version

ERPNext Version 14

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "14.8.0",
	"frappe": "14.16.0",
	"healthcare": "15.0.0-dev"
}
```
### Route
```
Form/Sales Invoice/new-sales-invoice-1
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1587, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 23, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 303, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 325, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 257, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1039, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 908, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1260, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1244, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/healthcare/healthcare/healthcare/utils.py", line 524, in manage_invoice_validate
    if doc.service_unit and len(doc.items):
AttributeError: 'HealthcareSalesInvoice' object has no attribute 'service_unit'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Sales Invoice\",\"name\":\"new-sales-invoice-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"22yogesh2001@gmail.com\",\"naming_series\":\"ACC-SINV-.YYYY.-\",\"company\":\"Agile Health\",\"posting_date\":\"2023-12-11\",\"set_posting_time\":0,\"is_pos\":0,\"is_consolidated\":0,\"is_return\":0,\"update_billed_amount_in_sales_order\":0,\"is_debit_note\":0,\"currency\":\"INR\",\"selling_price_list\":\"Standard Selling\",\"price_list_currency\":\"INR\",\"ignore_pricing_rule\":0,\"update_stock\":0,\"use_company_roundoff_cost_center\":0,\"disable_rounded_total\":0,\"apply_discount_on\":\"Grand Total\",\"is_cash_or_non_trade_discount\":0,\"total_billing_amount\":0,\"allocate_advances_automatically\":0,\"write_off_outstanding_amount_automatically\":0,\"redeem_loyalty_points\":0,\"ignore_default_payment_terms_template\":0,\"party_account_currency\":\"INR\",\"is_opening\":\"No\",\"group_same_items\":0,\"status\":\"Draft\",\"is_internal_customer\":0,\"is_discounted\":0,\"repost_required\":0,\"items\":[{\"docstatus\":0,\"doctype\":\"Sales Invoice Item\",\"name\":\"new-sales-invoice-item-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"22yogesh2001@gmail.com\",\"has_item_scanned\":0,\"stock_uom\":\"Nos\",\"margin_type\":\"\",\"is_free_item\":0,\"grant_commission\":1,\"delivered_by_supplier\":0,\"is_fixed_asset\":0,\"enable_deferred_revenue\":0,\"allow_zero_valuation_rate\":0,\"cost_center\":\"Main - AH\",\"page_break\":0,\"parent\":\"new-sales-invoice-1\",\"parentfield\":\"items\",\"parenttype\":\"Sales Invoice\",\"idx\":1,\"qty\":1,\"conversion_factor\":1,\"stock_qty\":1,\"price_list_rate\":20,\"base_price_list_rate\":20,\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":20,\"amount\":20,\"base_rate\":20,\"base_amount\":20,\"stock_uom_rate\":20,\"net_rate\":20,\"net_amount\":20,\"base_net_rate\":20,\"base_net_amount\":20,\"weight_per_unit\":0,\"total_weight\":0,\"incoming_rate\":0,\"actual_batch_qty\":0,\"actual_qty\":240,\"delivered_qty\":0,\"item_code\":\"dolo\",\"weight_uom\":null,\"barcode\":null,\"pricing_rules\":\"\",\"item_name\":\"Dolo 600mg\",\"description\":\"Dolo 600mg\",\"image\":\"\",\"warehouse\":\"Stores - AH\",\"income_account\":\"Sales - AH\",\"expense_account\":\"Cost of Goods Sold - AH\",\"discount_account\":null,\"provisional_expense_account\":null,\"has_serial_no\":0,\"has_batch_no\":0,\"batch_no\":null,\"uom\":\"Nos\",\"min_order_qty\":\"\",\"discount_percentage\":0,\"supplier\":null,\"update_stock\":0,\"last_purchase_rate\":0,\"transaction_date\":\"2023-12-11\",\"against_blanket_order\":null,\"bom_no\":null,\"item_group\":\"All Item Groups\",\"brand\":null,\"manufacturer\":null,\"manufacturer_part_no\":null,\"item_tax_rate\":\"{}\",\"customer_item_code\":null,\"valuation_rate\":20,\"projected_qty\":240,\"reserved_qty\":0,\"has_margin\":false,\"free_item_data\":\"\",\"child_docname\":\"new-sales-invoice-item-1\",\"gross_profit\":-20}],\"conversion_rate\":1,\"plc_conversion_rate\":1,\"company_tax_id\":null,\"company_address\":null,\"company_address_display\":null,\"posting_time\":\"17:11:55\",\"debit_to\":\"Debtors - AH\",\"base_net_total\":20,\"net_total\":20,\"base_total\":20,\"total\":20,\"total_qty\":1,\"rounding_adjustment\":0,\"grand_total\":20,\"base_grand_total\":20,\"total_taxes_and_charges\":0,\"base_total_taxes_and_charges\":0,\"base_rounding_adjustment\":0,\"rounded_total\":20,\"base_rounded_total\":20,\"in_words\":\"\",\"base_in_words\":\"\",\"base_discount_amount\":0,\"total_advance\":0,\"write_off_amount\":0,\"paid_amount\":0,\"base_paid_amount\":0,\"payments\":[],\"change_amount\":0,\"base_change_amount\":0,\"outstanding_amount\":20,\"amount_eligible_for_commission\":20,\"total_commission\":null,\"patient_name\":\"Kaivtha\",\"patient\":\"HLC-PAT-2023-00001\",\"customer\":\"Kaivtha\",\"tax_id\":null,\"customer_name\":\"Kaivtha\",\"loyalty_program\":null,\"represents_company\":null,\"due_date\":\"2023-12-11\",\"customer_address\":null,\"address_display\":null,\"shipping_address_name\":\"\",\"shipping_address\":null,\"contact_person\":null,\"contact_display\":null,\"contact_email\":null,\"contact_mobile\":null,\"customer_group\":\"All Customer Groups\",\"territory\":\"All Territories\",\"language\":\"en\",\"tax_category\":\"\",\"payment_terms_template\":null,\"sales_team\":[],\"total_net_weight\":0}",
		"action": "Save"
	},
	"btn": {
		"jQuery36000455798404576162051": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 7250,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exc_type": "DoesNotExistError",
	"exception": "AttributeError: 'HealthcareSalesInvoice' object has no attribute 'service_unit'"
}
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sajinsr** [comment]
This setup wont work since version 15 healthcare is incompatible with frappe/erpnext version-14.
Did you migrate the site?

**Comment by Yogeshwaran2210** [comment]
> This setup wont work since version 15 healthcare is incompatible with frappe/erpnext version-14. Did you migrate the site?

Now, I am using the `Healthcare` version 15 dev, now what can I do to move the version 14?

**Comment by Yogeshwaran2210** [comment]
> This setup wont work since version 15 healthcare is incompatible with frappe/erpnext version-14. Did you migrate the site?

I am migrate to version 14 only not version 15, are you working on this `Issue`..

**Comment by Sajinsr** [comment]
Can you do the migration by checking out to healthcare version-14?

**Comment by Yogeshwaran2210** [comment]
> Can you do the migration by checking out to healthcare version-14?

Yes..Now, what I do to solve it?

**Comment by Sajinsr** [comment]
@Yogeshwaran2210 Basically you'll need to run this patch.
https://github.com/frappe/health/blob/version-14/healthcare/patches/v15_0/create_custom_fields_in_sales_invoice_item.py

**Comment by Yogeshwaran2210** [comment]
> @Yogeshwaran2210 Basically you'll need to run this patch. https://github.com/frappe/health/blob/version-14/healthcare/patches/v15_0/create_custom_fields_in_sales_invoice_item.py

**`Thank You for the Help.`**
Is there is any cmd to run this patch in the server?
And, I have already have that patch file you mentioned above. The above patch file & in my file are same.
Now, What I do with this?
