### ISSUE TITLE
ModuleNotFoundError: No module named 'health'

### ISSUE THREAD

**Issue by Margishnextbrain** [earthians/marley#358]
### Information about bug

i am not able to install application 
ModuleNotFoundError: No module named 'health'

bench --site margish.com install-app healthcare
getting the below error

(base) developer@nextbrain-Latitude-5480:~/Desktop/Frappe/frappe-bench$ **bench --site margish.com install-app healthcare**
Traceback (most recent call last):
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 75, in get_app_commands
    app_command_module = importlib.import_module(f"{app}.commands")
  File "/home/developer/miniforge3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'health'
Traceback (most recent call last):
  File "/home/developer/miniforge3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/developer/miniforge3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/developer/Desktop/Frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/developer/Desktop/Frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/developer/Desktop/Frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/developer/Desktop/Frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/developer/Desktop/Frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/developer/Desktop/Frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/developer/Desktop/Frappe/frappe-bench/env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 456, in install_app
    frappe.init(site=site)
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 284, in init
    setup_module_map()
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1646, in setup_module_map
    for module in get_module_list(app):
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1505, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1470, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1500, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/home/developer/miniforge3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'health'

@rmehta @akurungadam @nabinhait 
please let me  now how to install frappe/health in ubuntu
readme file not able to install also i have install Erpnext.

### Module

Integration with ERPNext modules

### Version

Frappe version:14

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
PLease help me out to installation in ubuntu manually.
please share some proper redme file or video

(base) developer@nextbrain-Latitude-5480:~/Desktop/Frappe/frappe-bench$ bench --site margish.com install-app healthcare
Traceback (most recent call last):
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 75, in get_app_commands
    app_command_module = importlib.import_module(f"{app}.commands")
  File "/home/developer/miniforge3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'health'
Traceback (most recent call last):
  File "/home/developer/miniforge3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/developer/miniforge3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/developer/Desktop/Frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/developer/Desktop/Frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/developer/Desktop/Frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/developer/Desktop/Frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/developer/Desktop/Frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/developer/Desktop/Frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/developer/Desktop/Frappe/frappe-bench/env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 456, in install_app
    frappe.init(site=site)
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 284, in init
    setup_module_map()
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1646, in setup_module_map
    for module in get_module_list(app):
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1505, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1470, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1500, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/home/developer/miniforge3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'health'

=================================================================



while db migrate time error

      package = None
      level = 0
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      name = 'health'
      package = None
      level = 0
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      name = 'health'
      import_ = <function _gcd_import at 0x7f16daa4f400>
      module = <object object at 0x7f16daa74060>
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
      name = 'health'
      import_ = <function _gcd_import at 0x7f16daa4f400>
      path = None
      parent = ''
      spec = None
builtins.ModuleNotFoundError: No module named 'health'



==========================================================================

(base) developer@-Latitude-5480:~/Desktop/Frappe/frappe-bench$ bench get-app healthcare
A directory for the application 'healthcare' already exists. Do you want to continue and overwrite it? [y/N]: y
INFO: App moved from apps/healthcare to archived/apps/healthcare-2023-12-22_1
Getting healthcare
$ git clone https://github.com/frappe/healthcare.git --branch version-14 --depth 1 --origin upstream
Cloning into 'healthcare'...
remote: Enumerating objects: 588, done.
remote: Counting objects: 100% (588/588), done.
remote: Compressing objects: 100% (510/510), done.
remote: Total 588 (delta 176), reused 235 (delta 54), pack-reused 0
Receiving objects: 100% (588/588), 1019.52 KiB | 2.08 MiB/s, done.
Resolving deltas: 100% (176/176), done.
Ignoring dependencies of healthcare. To install dependencies use --resolve-deps
Installing healthcare
$ /home/developer/Desktop/Frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade -e /home/developer/Desktop/Frappe/frappe-bench/apps/healthcare 
$ bench build --app healthcare
Traceback (most recent call last):
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 75, in get_app_commands
    app_command_module = importlib.import_module(f"{app}.commands")
  File "/home/developer/miniforge3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'health'
Traceback (most recent call last):
  File "/home/developer/miniforge3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/developer/miniforge3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 114, in <module>
    main()
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 20, in main
    click.Group(commands=commands)(prog_name="bench")
  File "/home/developer/Desktop/Frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/developer/Desktop/Frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/developer/Desktop/Frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/developer/Desktop/Frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1685, in invoke
    super().invoke(ctx)
  File "/home/developer/Desktop/Frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/developer/Desktop/Frappe/frappe-bench/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/developer/Desktop/Frappe/frappe-bench/env/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 44, in app_group
    ctx.obj = {"sites": get_sites(site), "force": force, "verbose": verbose, "profile": profile}
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 56, in get_sites
    elif default_site := frappe.get_conf().default_site:
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 410, in get_conf
    with init_site(site):
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 420, in __enter__
    init(self.site)
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 284, in init
    setup_module_map()
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1646, in setup_module_map
    for module in get_module_list(app):
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1505, in get_module_list
    return get_file_items(get_app_path(app_name, "modules.txt"))
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1470, in get_app_path
    return get_pymodule_path(app_name, *joins)
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1500, in get_pymodule_path
    return abspath(join(dirname(get_module(scrub(modulename)).__file__ or ""), *joins))
  File "/home/developer/Desktop/Frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1441, in get_module
    return importlib.import_module(modulename)
  File "/home/developer/miniforge3/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'health'
ERROR: bench build --app healthcare
subprocess.CalledProcessError: Command 'bench build --app healthcare' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/developer/miniforge3/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/home/developer/miniforge3/lib/python3.10/site-packages/bench/cli.py", line 132, in cli
    bench_command()
  File "/home/developer/miniforge3/lib/python3.10/site-packages/bench/commands/make.py", line 167, in get_app
    get_app(
  File "/home/developer/miniforge3/lib/python3.10/site-packages/bench/app.py", line 444, in get_app
    app.install(verbose=verbose, skip_assets=skip_assets, restart_bench=restart_bench)
  File "/home/developer/miniforge3/lib/python3.10/site-packages/bench/utils/render.py", line 126, in wrapper_fn
    return fn(*args, **kwargs)
  File "/home/developer/miniforge3/lib/python3.10/site-packages/bench/app.py", line 242, in install
    install_app(
  File "/home/developer/miniforge3/lib/python3.10/site-packages/bench/app.py", line 586, in install_app
    build_assets(bench_path=bench_path, app=app)
  File "/home/developer/miniforge3/lib/python3.10/site-packages/bench/utils/bench.py", line 351, in build_assets
    exec_cmd(command, cwd=bench_path, env={"BENCH_DEVELOPER": "1"})
  File "/home/developer/miniforge3/lib/python3.10/site-packages/bench/utils/__init__.py", line 158, in exec_cmd
    raise CommandFailedError(cmd) from subprocess.CalledProcessError(return_code, cmd)
bench.exceptions.CommandFailedError: bench build --app healthcare
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by akashkrishna619** [comment]
@Margishnextbrain tried on a fresh bench and couldn't replicate this issue,
if you share what steps you followed to get this error will be helpful for me to replicate this.

**Comment by Margishnextbrain** [comment]
(base) developer@nextbrain-Latitude-5480:~/Frappe/frappe-bench$ bench --site mysite.local install-app erpnext

Installing erpnext...
Updating DocTypes for erpnext       : [========================================] 100%
Updating customizations for Address
Updating customizations for Contact
(base) developer@nextbrain-Latitude-5480:~/Frappe/frappe-bench$ bench start
01:42:48 system        | redis_cache.1 started (pid=1088911)
01:42:48 system        | redis_queue.1 started (pid=1088914)
01:42:48 system        | socketio.1 started (pid=1088922)
01:42:48 redis_cache.1 | 1088923:C 24 Dec 2023 01:42:48.684 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
01:42:48 redis_cache.1 | 1088923:C 24 Dec 2023 01:42:48.685 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=1088923, just started
01:42:48 redis_cache.1 | 1088923:C 24 Dec 2023 01:42:48.685 # Configuration loaded
01:42:48 redis_cache.1 | 1088923:M 24 Dec 2023 01:42:48.686 * Increased maximum number of open files to 10032 (it was originally set to 1024).
01:42:48 redis_cache.1 | 1088923:M 24 Dec 2023 01:42:48.687 # Could not create server TCP listening socket 127.0.0.1:13000: bind: Address already in use
01:42:48 system        | redis_cache.1 stopped (rc=1)
01:42:48 redis_queue.1 | 1088921:C 24 Dec 2023 01:42:48.690 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
01:42:48 redis_queue.1 | 1088921:C 24 Dec 2023 01:42:48.691 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=1088921, just started
01:42:48 system        | web.1 started (pid=1088924)
01:42:48 redis_queue.1 | 1088921:C 24 Dec 2023 01:42:48.691 # Configuration loaded
01:42:48 system        | schedule.1 started (pid=1088926)
01:42:48 redis_queue.1 | 1088921:M 24 Dec 2023 01:42:48.692 * Increased maximum number of open files to 10032 (it was originally set to 1024).
01:42:48 redis_queue.1 | 1088921:M 24 Dec 2023 01:42:48.693 # Could not create server TCP listening socket 127.0.0.1:11000: bind: Address already in use
01:42:48 system        | redis_queue.1 stopped (rc=1)
01:42:48 system        | worker.1 started (pid=1088935)
01:42:48 system        | watch.1 started (pid=1088932)
01:42:48 system        | sending SIGTERM to web.1 (pid 1088924)
01:42:48 system        | sending SIGTERM to socketio.1 (pid 1088922)
01:42:48 system        | sending SIGTERM to watch.1 (pid 1088932)
01:42:48 system        | sending SIGTERM to schedule.1 (pid 1088926)
01:42:48 system        | sending SIGTERM to worker.1 (pid 1088935)
01:42:48 system        | schedule.1 stopped (rc=-15)
01:42:48 system        | watch.1 stopped (rc=-15)
01:42:48 system        | web.1 stopped (rc=-15)
01:42:48 system        | socketio.1 stopped (rc=-15)
01:42:48 system        | worker.1 stopped (rc=-15)

==================================================================================
(base) developer@nextbrain-Latitude-5480:~/Frappe/frappe-bench$ bench start
01:45:18 system        | redis_cache.1 started (pid=1251671)
01:45:18 system        | redis_queue.1 started (pid=1251674)
01:45:18 redis_cache.1 | 1251678:C 24 Dec 2023 01:45:18.611 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
01:45:18 system        | socketio.1 started (pid=1251683)
01:45:18 redis_cache.1 | 1251678:C 24 Dec 2023 01:45:18.614 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=1251678, just started
01:45:18 redis_cache.1 | 1251678:C 24 Dec 2023 01:45:18.614 # Configuration loaded
01:45:18 redis_cache.1 | 1251678:M 24 Dec 2023 01:45:18.615 * Increased maximum number of open files to 10032 (it was originally set to 1024).
01:45:18 redis_cache.1 | 1251678:M 24 Dec 2023 01:45:18.616 # Could not create server TCP listening socket 127.0.0.1:13000: bind: Address already in use
01:45:18 redis_queue.1 | 1251685:C 24 Dec 2023 01:45:18.617 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
01:45:18 system        | redis_cache.1 stopped (rc=1)
01:45:18 redis_queue.1 | 1251685:C 24 Dec 2023 01:45:18.618 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=1251685, just started
01:45:18 system        | web.1 started (pid=1251682)
01:45:18 redis_queue.1 | 1251685:C 24 Dec 2023 01:45:18.618 # Configuration loaded
01:45:18 system        | worker.1 started (pid=1251686)
01:45:18 redis_queue.1 | 1251685:M 24 Dec 2023 01:45:18.620 * Increased maximum number of open files to 10032 (it was originally set to 1024).
01:45:18 redis_queue.1 | 1251685:M 24 Dec 2023 01:45:18.620 # Could not create server TCP listening socket 127.0.0.1:11000: bind: Address already in use
01:45:18 system        | redis_queue.1 stopped (rc=1)
01:45:18 system        | watch.1 started (pid=1251687)
01:45:18 system        | schedule.1 started (pid=1251696)
01:45:18 system        | sending SIGTERM to web.1 (pid 1251682)
01:45:18 system        | sending SIGTERM to socketio.1 (pid 1251683)
01:45:18 system        | sending SIGTERM to watch.1 (pid 1251687)
01:45:18 system        | sending SIGTERM to schedule.1 (pid 1251696)
01:45:18 system        | sending SIGTERM to worker.1 (pid 1251686)
01:45:18 system        | worker.1 stopped (rc=-15)
01:45:18 system        | web.1 stopped (rc=-15)
01:45:18 system        | socketio.1 stopped (rc=-15)
01:45:18 system        | schedule.1 stopped (rc=-15)
01:45:18 system        | watch.1 stopped (rc=-15)

@akashkrishna619 i am not able to run the bench start.
i am following below document
https://github.com/D-codE-Hub/ERPNext-installation-Guide/blob/main/README.md
can you please suggest me

Thanks

**Comment by imbraintl** [comment]
Try to use the below installation steps.

https://github.com/kalungia/How-to-Install-ERPNext-on-Ubuntu-22.04-LTS

**Comment by Margishnextbrain** [comment]
@imbraintl same issue version error.

**Comment by Margishnextbrain** [comment]
Please share the easy installation step

**Comment by Margishnextbrain** [comment]
Please share the easy installation step

**Comment by Feeh03114** [comment]
I'm using docker and docker compose and it's showing the same error

**Comment by Sajinsr** [comment]
Hi, is this issue still exist? the repo is now available [here](https://github.com/earthians/marley)
can you check the remote and pull the latest and try again? closing this issue for now.
