### ISSUE TITLE
"Resource not found" error upon saving of Discharge Summary.

### ISSUE THREAD

**Issue by Muthana-Ali** [earthians/marley#551]
### Information about bug

**Objective**: Discharging a patient from the Inpatient Record doctype and seeing a Discharged status or anything similar.
**Requirements**: A discharge summary is required for discharging a patient from the Inpatient Record.
**Problem**: Upon saving the Discharge Summary from the Create -> Discharge Summary from the Inpatient Record entry, given filling all the mandatory fields and the non-mandatory filed provides this error shown below.

![photo_2024-12-17_12-13-58](https://github.com/user-attachments/assets/aea93ba3-cfc3-4099-abd7-350c2e5f062a)

The video below shows the procedure in details.

https://github.com/user-attachments/assets/dc5db6a8-ac5c-4c1e-b841-98094a127949

### Module

Inpatient ADT

### Version

15.x.x-develop - 15.x.x-develop - 16.0.0-dev

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
request.js:280 
        
        
       POST http://203.161.63.230/api/method/frappe.desk.form.save.savedocs 404 (NOT FOUND)
send @ jquery.js:9930
ajax @ jquery.js:9511
frappe.request.call @ request.js:280
frappe.call @ request.js:110
_call @ save.js:199
save @ save.js:21
frappe.ui.form.save @ save.js:226
(anonymous) @ form.js:841
Promise.then
(anonymous) @ dom.js:276
frappe.run_serially @ dom.js:274
validate_and_save @ form.js:832
(anonymous) @ form.js:771
save @ form.js:768
Save @ toolbar.js:745
(anonymous) @ page.js:311
dispatch @ jquery.js:5135
elemData.handle @ jquery.js:4939
request.js:363 Unable to handle failed response
request.js:364 TypeError: Cannot read properties of undefined (reading 'exc')
    at after_save (form.js:789:11)
    at Object.error [as error_callback] (save.js:29:6)
    at 404 (request.js:150:32)
    at Object.<anonymous> (request.js:357:6)
    at fire (jquery.js:3213:31)
    at Object.fireWith [as rejectWith] (jquery.js:3343:7)
    at done (jquery.js:9619:14)
    at XMLHttpRequest.<anonymous> (jquery.js:9878:9)
overrideMethod @ hook.js:608
(anonymous) @ request.js:364
fire @ jquery.js:3213
fireWith @ jquery.js:3343
done @ jquery.js:9619
(anonymous) @ jquery.js:9878
load
send @ jquery.js:9897
ajax @ jquery.js:9511
frappe.request.call @ request.js:280
frappe.call @ request.js:110
_call @ save.js:199
save @ save.js:21
frappe.ui.form.save @ save.js:226
(anonymous) @ form.js:841
Promise.then
(anonymous) @ dom.js:276
frappe.run_serially @ dom.js:274
validate_and_save @ form.js:832
(anonymous) @ form.js:771
save @ form.js:768
Save @ toolbar.js:745
(anonymous) @ page.js:311
dispatch @ jquery.js:5135
elemData.handle @ jquery.js:4939

request.js:280 
        
        
       POST http://203.161.63.230/api/method/frappe.desk.form.save.savedocs 404 (NOT FOUND)
send @ jquery.js:9930
ajax @ jquery.js:9511
frappe.request.call @ request.js:280
frappe.call @ request.js:110
_call @ save.js:199
save @ save.js:21
frappe.ui.form.save @ save.js:226
(anonymous) @ form.js:841
Promise.then
(anonymous) @ dom.js:276
frappe.run_serially @ dom.js:274
validate_and_save @ form.js:832
(anonymous) @ form.js:771
save @ form.js:768
Save @ toolbar.js:745
(anonymous) @ page.js:311
dispatch @ jquery.js:5135
elemData.handle @ jquery.js:4939
request.js:363 Unable to handle failed response
request.js:364 TypeError: Cannot read properties of undefined (reading 'exc')
    at after_save (form.js:789:11)
    at Object.error [as error_callback] (save.js:29:6)
    at 404 (request.js:150:32)
    at Object.<anonymous> (request.js:357:6)
    at fire (jquery.js:3213:31)
    at Object.fireWith [as rejectWith] (jquery.js:3343:7)
    at done (jquery.js:9619:14)
    at XMLHttpRequest.<anonymous> (jquery.js:9878:9)
overrideMethod @ hook.js:608
(anonymous) @ request.js:364
fire @ jquery.js:3213
fireWith @ jquery.js:3343
done @ jquery.js:9619
(anonymous) @ jquery.js:9878
load
send @ jquery.js:9897
ajax @ jquery.js:9511
frappe.request.call @ request.js:280
frappe.call @ request.js:110
_call @ save.js:199
save @ save.js:21
frappe.ui.form.save @ save.js:226
(anonymous) @ form.js:841
Promise.then
(anonymous) @ dom.js:276
frappe.run_serially @ dom.js:274
validate_and_save @ form.js:832
(anonymous) @ form.js:771
save @ form.js:768
Save @ toolbar.js:745
(anonymous) @ page.js:311
dispatch @ jquery.js:5135
elemData.handle @ jquery.js:4939
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Muthana-Ali** [comment]
Solved by making at least one Patient Encounter for that Patient.
