### ISSUE TITLE
An error occurred while installing healthcare: Item cannot be added to its own descendents

### ISSUE THREAD

**Issue by netsec-yogi** [earthians/marley#86]
Recently Facing this issue while installing, hence missing lots of doctypes of healthcare app in the dashboard.
.
Installing healthcare...
Updating DocTypes for healthcare    : [========================================] 100%
An error occurred while installing healthcare: Item cannot be added to its own descendents
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 344, in install_app
    _install_app(app, verbose=context.verbose)
  File "apps/frappe/frappe/installer.py", line 178, in install_app
    frappe.get_attr(after_install)()
  File "apps/healthcare/healthcare/setup.py", line 81, in setup_healthcare
    create_custom_records()
  File "apps/healthcare/healthcare/setup.py", line 90, in create_custom_records
    create_healthcare_item_groups()
  File "apps/healthcare/healthcare/setup.py", line 276, in create_healthcare_item_groups
    insert_record(records)
  File "apps/erpnext/erpnext/setup/utils.py", line 158, in insert_record
    doc.insert(ignore_permissions=True, ignore_if_duplicate=True)
  File "apps/frappe/frappe/model/document.py", line 267, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1009, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 873, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1170, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1153, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 870, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/setup/doctype/item_group/item_group.py", line 40, in on_update
    NestedSet.on_update(self)
  File "apps/frappe/frappe/utils/nestedset.py", line 210, in on_update
    update_nsm(self)
  File "apps/frappe/frappe/utils/nestedset.py", line 40, in update_nsm
    update_add_node(doc, parent or '', parent_field)
  File "apps/frappe/frappe/utils/nestedset.py", line 62, in update_add_node
    validate_loop(doc.doctype, doc.name, left, right)
  File "apps/frappe/frappe/utils/nestedset.py", line 202, in validate_loop
    frappe.throw(_("Item cannot be added to its own descendents"), NestedSetRecursionError)
  File "apps/frappe/frappe/__init__.py", line 447, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "apps/frappe/frappe/__init__.py", line 426, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 381, in _raise_exception
    raise raise_exception(msg)
frappe.utils.nestedset.NestedSetRecursionError: Item cannot be added to its own descendents

**Comment by ChillarAnand** [comment]
@iitindore-citc We have pushed a fix for this in the latest `develop` branch. Pull the latest changes and reinstall it.

Feel free to re-open if you face any other issues.
